### PR TITLE
WIP Update for DLC Save

### PR DESCRIPTION
**Pull request by EthanShoeDev**
I added a few tests and fixed the ability to **read** data from a save (I needed that for my [side project](https://elden-ring-compass.vercel.app/))

This PR is more to start a discussion on making this project compatible with post dlc saves. :)

Oh and I ran `cargo fmt` which resulted in many lines changed. Perhaps we can do that on a separate PR?

### CODE REVIEW

**Comment by EthanShoeDev** [comment]
Related: 
- https://github.com/ClayAmore/ER-Save-Editor/issues/32
- https://github.com/ClayAmore/ER-Save-Editor/issues/31
- https://github.com/ClayAmore/ER-Save-Editor/issues/28

**Comment by elendil7** [comment]
Progress 💪

**Comment by ClayAmore** [comment]
Hey Ethan,

This is pretty cool!

I've made some good progress on making this compatible with DLC saves. I can already open PC saves, and I believe with one more session, I'll be able to open PS saves as well.

Regarding the assert, unfortunately, it's not the root of the problem. The byte I'm checking should indeed be 0. The main issue is that the regulation.bin file, which is backed up in user_data_11, has increased in size due to additional parameters being added. I've adjusted the hardcoded sizes to accommodate this change. Additionally, it appears that FS has switched the compression algorithm to [zstd](https://github.com/facebook/zstd). I tested decompressing the bytes using the [rust zstd crate](https://docs.rs/zstd/latest/zstd/), and it works perfectly.

I hope to update the repo with a functional version in a few days. Regarding a release, I'll need to consider how to handle the DLC content. I'm not sure if I can determine if a player owns the DLC from the save file. If I can't, there’s a risk of players getting banned if they unlock and equip undroppable items like DLC spells. Besides that, there are several bugs that need fixing, and I plan to add proper error reporting for crashes.

I have limited free time lately, but I’ll try to keep people updated on the progress.

**Comment by EthanShoeDev** [comment]
@ClayAmore That's awesome! Thanks so much for making the project. I am very much a rust noob so this has been fun to play with.

I also got the zstd crate to decrypt the reg but broke many other things to get there :)

Closing this for now

**Comment by L0RDT1TAN** [comment]
It Is still crashing for me. Has this been fixed ?

**Comment by jacobthebossie** [comment]
Has it been fixed

**Pull request closed without merging**
